feat: Integrating Sitemap using next-sitemap package
avorg/audioverse-next pull request #255
Opened 2022-03-17 19:48 UTC by leonboripgs

2022-03-18 16:35 UTC, narthur approved these changes
Looks good!

Can you help me understand which pages do and don't get included and why? Thanks!

https://audioverse-next-git-fork-leonboripgs-sitemap-audioverse.vercel.app/sitemap-0.xml

2022-03-22 16:18 UTC, mattleff requested changes
It appears this only includes the pages that are being pre-rendered. I don't know if that's a problem or not...

2022-03-22 16:18 UTC, mattleff commented on next-sitemap.js
> +	generateRobotsTxt: true,
This doesn't appear to be working since the `public/robots.txt` exists.

2022-04-04 01:10 UTC, marcomiduri commented
@mattleff @narthur Would you please check the PR again?

2022-04-04 01:56 UTC, marcomiduri commented
> Looks good!
> 
> Can you help me understand which pages do and don't get included and why? Thanks!
> 
> https://audioverse-next-git-fork-leonboripgs-sitemap-audioverse.vercel.app/sitemap-0.xml

@narthur Since we didn't set the configuration like `exclude`, all pages are added to XML file because `next-sitemap` command checks all generated HTML files and add them to sitemap. You can review this link https://github.com/iamvishnusankar/next-sitemap#configuration-options

2022-04-04 19:18 UTC, narthur approved these changes
Changes look good. After talking with @mattleff I'm fine with the sitemap not including pages that aren't created at build time.

2022-04-04 19:29 UTC, marcomiduri commented
> Changes look good. After talking with @mattleff I'm fine with the sitemap not including pages that aren't created at build time.

@narthur Thanks for your review, do you know why the build is failed on github action?

2022-04-04 19:53 UTC, mattleff approved these changes

2022-04-06 15:13 UTC, merged