feat: add videojs-airplay, videojs-chromecast
avorg/audioverse-next pull request #262
Opened 2022-04-04 20:58 UTC by leonboripgs

Hello, I created new PR for airplay/chromecast again regarding original one have some linting issue and structure problems.
Please review the PR and let me know your feedbacks.
Thanks.

2022-04-05 13:47 UTC, narthur requested changes

2022-04-05 13:47 UTC, narthur commented on src/components/templates/andPlaybackContext.tsx
> +// import airplay from '../../lib/videojs-airplay/dist/silvermine-videojs-airplay';
Can we remove this?

2022-04-05 13:47 UTC, narthur commented on src/components/templates/andPlaybackContext.tsx
> +				console.log(p);
Maybe some testing code slipped through?

2022-04-06 14:37 UTC, marcomiduri commented on src/components/templates/andPlaybackContext.tsx
> +// import airplay from '../../lib/videojs-airplay/dist/silvermine-videojs-airplay';
@narthur I removed this code.

2022-04-06 14:38 UTC, marcomiduri commented on src/components/templates/andPlaybackContext.tsx
> +				console.log(p);
@narthur I removed this code.

2022-04-06 14:44 UTC, narthur approved these changes
Great work!

2022-04-06 14:45 UTC, mattleff requested changes
@leonboripgs Can you `nvm use` & `npm i` to ensure the lock file isn't changing versions?

2022-04-11 10:05 UTC, marcomiduri commented
@mattleff To fix massive package-lock.json file update, I am closing this PR and created another cloned one. https://github.com/avorg/audioverse-next/pull/268

2022-04-11 10:05 UTC, marcomiduri commented
@mattleff To fix massive package-lock.json file update, I am closing this PR and created another cloned one. https://github.com/avorg/audioverse-next/pull/268

2022-04-11 10:05 UTC, closed without merging