Import videojs-chromcast and videojs-airplay
avorg/audioverse-next pull request #268
Opened 2022-04-11 10:03 UTC by marcomiduri

@mattleff It looks like we got some test errors to fix. Would you please explain in detail? How does the test work in the codebase?

2022-04-11 21:29 UTC, mattleff requested changes

2022-04-11 21:29 UTC, mattleff commented on src/components/templates/andPlaybackContext.tsx
> +						addButtonToControlBar: false,
I think this is correct because we want to use a custom button, but it doesn't look it's been added to this PR. Here's the designs for the buttons: https://www.figma.com/file/SKSajWfEkf56GQfZyI2S4a/Design-System?node-id=5073%3A258263 + https://www.figma.com/file/SKSajWfEkf56GQfZyI2S4a/Design-System?node-id=5093%3A256915.

2022-04-11 21:29 UTC, mattleff commented on src/components/templates/andPlaybackContext.tsx
> +			require('@silvermine/videojs-airplay')(v.default);
Similarly to #269 this should use `import()` instead of `require()` to avoid bloating the global bundle.

2022-04-11 21:29 UTC, mattleff commented on src/styles/styles.scss
> +@import '../../node_modules/@silvermine/videojs-airplay/dist/silvermine-videojs-airplay.css';
Are these needed if we're using custom buttons?

2022-04-11 21:41 UTC, mattleff commented
@marcomiduri Re: test failures - We have a function that mocks Video.js when in test and you may need to update that mock to work with the AirPlay and Chromecast plugins: https://github.com/avorg/audioverse-next/blob/master/src/lib/test/helpers.tsx#L261

2022-04-12 03:12 UTC, leonboripgs reviewed
Just left few comments on the PR, once I get reply for them, I will approve it. Thank you.

2022-04-12 03:12 UTC, leonboripgs commented on src/components/templates/andPlaybackContext.tsx
> +			require('@silvermine/videojs-airplay')(v.default);
* Just from my understanding import `video.js` should be done from the global side rather than at component level. Currently importing will be duplicated which is not the best practice.
* Instead of var requires (force terminated the eslint check), need to use ES6 style import.

2022-04-12 03:12 UTC, leonboripgs commented on src/components/templates/andPlaybackContext.tsx
> +					require('@silvermine/videojs-airplay')(videoJsImport);
The same thing applies to here.

2022-04-12 03:12 UTC, leonboripgs commented on src/styles/styles.scss
> +@import '../../node_modules/@silvermine/videojs-airplay/dist/silvermine-videojs-airplay.css';
This style is not only for the buttons guess there are much more. Btw, from the documentation seems like better way to import styles and override variables which seems better than this.
`@import "path/to/node_modules/@silvermine/videojs-airplay/src/scss/videojs-airplay";`
And here - https://github.com/silvermine/videojs-airplay#using-the-css-and-images 
Maybe need to add the default buttons and customize the styles using this section.

2022-04-12 03:12 UTC, leonboripgs commented on src/components/templates/andPlaybackContext.tsx
> +						addButtonToControlBar: false,
We are going to add custom buttons to here, but with difference appearance. What about `addButtonToControllBar: true` (by default) and customize it using the styles?

https://github.com/silvermine/videojs-airplay#using-the-css-and-images

2022-04-20 09:47 UTC, marcomiduri commented on src/components/templates/andPlaybackContext.tsx
> +			require('@silvermine/videojs-airplay')(v.default);
@mattleff I have fixed this issue

2022-07-11 19:54 UTC, merged