Fullscreen player
avorg/audioverse-next pull request #269
Opened 2022-04-11 10:21 UTC by marcomiduri

2022-04-11 20:32 UTC, mattleff requested changes

2022-04-11 20:32 UTC, mattleff commented on src/components/molecules/languageButton.tsx
> -import { Language } from '@lib/generated/graphql';
The changes in this file were made in #265, so they should be removed.

2022-04-11 20:32 UTC, mattleff commented on src/lib/constants.ts
> +export type SupportedLanguages = Exclude<Language, 'NORDIC'>;
The changes in this file were made in #265, so they should be removed.

2022-04-11 20:32 UTC, mattleff commented on src/components/templates/andPlaybackContext.tsx
> +			require('videojs-overlay');
This should use `import()` to avoid increasing the global bundle size. Could we do something like:

```
Promise.all([
    import('video.js'),
    import('videojs-overlay')
]).then(([v]) => {
    setVideojs(v);
})
```

2022-04-11 20:32 UTC, mattleff commented on src/components/templates/andMiniplayer.tsx
> +	console.log(recording);
Nix

2022-04-11 20:32 UTC, mattleff commented on src/components/templates/andMiniplayer.tsx
> +								Part {teaseRecording?.sequenceIndex} of{' '}
This needs internationalization (i18n):

```
<FormattedMessage
    id="andMiniplayer__partOfPart"
    defaultMessage="Part {index} of {total}"
    values={{
        index: teaseRecording?.sequenceIndex,
        total: teaseRecording?.sequence?.recordings.nodes?.length
    }}
/>
```

2022-04-11 20:32 UTC, mattleff commented on src/components/templates/andMiniplayer.tsx
> +				{player?.isFullscreen && <LazyMiniplayerOverlay />}
Should this be `player?.isFullscreen()` ([ref](https://docs.videojs.com/player#isFullscreen))?

2022-04-11 21:22 UTC, mattleff commented
@leonboripgs I've tested the functionality and there are a few bugs we need to address:

After entering the fullscreen view and pausing the video there is a small gap on the left edge (or sometimes the top edge) of the screen where the overlay doesn't reach the the left (or top) edge:

<img width="82" alt="image" src="https://user-images.githubusercontent.com/120155/162833519-408a2735-2e65-4100-8b6b-1eecd74c6333.png">

From the fullscreen view there should be a button to exit the fullscreen overlay ([ref](https://www.figma.com/file/SKSajWfEkf56GQfZyI2S4a/Design-System?node-id=1315%3A95382)):

<img width="242" alt="image" src="https://user-images.githubusercontent.com/120155/162833925-5e3cbe4a-acb2-4d44-bf36-513b3b6adc5f.png">

The play, pause, and nudge buttons in the overlay miniplayer should all be salmon instead of red. The key line at the top edge of the overlay miniplayer should be mid tone instead of white.

The font of the video and series titles in the paused view should be IvyJournal instead of Inter. The speaker avatar should be round instead of square. The speaker name should be light tone instead of white. The media type icon should be salmon instead of red. 

When a recording is not part of a series (such as https://audioverse-next-git-feat-player-fullscreen-audioverse.vercel.app/en/teachings/21929/when-god-stretches-our-faith) there should not be a `Part of` line in the fullscreen paused view:

<img width="189" alt="image" src="https://user-images.githubusercontent.com/120155/162834421-4251a904-ce91-465c-8798-46b78a8f706e.png">

When a recording does not have a speaker (such as https://audioverse-next-git-feat-player-fullscreen-audioverse.vercel.app/en/teachings/1681/asi-members-in-action) there should not be an error thrown when attempting to enter fullscreen view:

> TypeError: undefined is not an object (evaluating 'b.speakers[0].imageWithFallback') — https://audioverse-next-git-feat-player-fullscreen…next/static/chunks/pages/_app-687ed973e85abd90.js:0

2022-04-12 00:40 UTC, marcomiduri commented on src/components/templates/andPlaybackContext.tsx
> +			require('videojs-overlay');
`videojs-overlay` library doesn't support typescript. I assume that's why @leonboripgs used require function

2022-04-12 00:42 UTC, marcomiduri commented on src/components/templates/andMiniplayer.tsx
> +				{player?.isFullscreen && <LazyMiniplayerOverlay />}
@mattleff yes correct, maybe that's typo.

2022-04-12 03:23 UTC, leonboripgs reviewed
Overall LGTM. Only few cosmetic fix needed (only one maybe).

2022-04-12 03:23 UTC, leonboripgs commented on src/components/organisms/miniplayerOverlay.tsx
> +					{/*TODO: Get rid of ID; use ref instead*/}
Is this going to come soon?

2022-04-12 03:23 UTC, leonboripgs commented on src/components/organisms/miniplayerOverlay.tsx
> +						onChange={(e, val) => playbackContext.setVolume(val as number)}
Type enforcement is not welcome at typescript actually maybe need to friendly convert into number using `Number(val)` function.

2022-04-12 03:23 UTC, leonboripgs commented on src/components/templates/andPlaybackContext.tsx
> +			require('videojs-overlay');
I prefer ES6 import style than the `require` statement. I think we can improve this.

2022-04-13 19:37 UTC, marcomiduri commented on src/components/templates/andPlaybackContext.tsx
> +			require('videojs-overlay');
@leonboripgs I saw your code. require statement is not an async function and it doesn't respond Promise value. Is this intentional?

2022-04-20 09:59 UTC, closed without merging