HelpScout integration
avorg/audioverse-next pull request #285
Opened 2022-05-11 17:27 UTC by narthur

2022-05-26 15:55 UTC, mattleff requested changes
Looks good overall! It seems the checks have stopped running and I think they would catch a few issues I noted in the comments. I also think the additional langs need a `npm run extract && npm run compile`.

2022-05-26 15:55 UTC, mattleff commented on .eslintrc.js
> +			2,
Should this (and below) be `error` or `warn`?

2022-05-26 15:55 UTC, mattleff commented on src/components/templates/andPlaybackContext.tsx
> -	useEffect(() => {
Don't we still need this?

2022-05-26 15:55 UTC, mattleff commented on src/lib/getIntlMessages.ts
> +	return lang?.messages || {};
I think not using `import()` here will increase the bundle size.

2022-05-26 15:55 UTC, mattleff commented on src/lib/getNavigationItems.tsx
> +				{
AFAIK, this is for HelpScout.

2022-05-26 15:55 UTC, mattleff commented on tsconfig.json
> +			"@root/*": ["*"]
Is this change needed?

2022-05-26 16:12 UTC, mattleff commented
@narthur The changes in this PR have significant bundle implications. I've highlighted a couple of them in my comments.

2022-05-26 16:15 UTC, mattleff commented on src/components/templates/andPlaybackContext.tsx
> -			} else if (videojs) {
I believe this reintroduces the bug #225 fixed.

2022-05-26 17:53 UTC, narthur commented on tsconfig.json
> +			"@root/*": ["*"]
Good catch, resolved!

2022-05-27 13:37 UTC, narthur commented
@mattleff I just ran `npm run extract && npm run compile` and it didn't result in any changes... 😕

2022-05-30 18:14 UTC, mattleff requested changes
Looks great, except for the Safari two-click bug

2022-05-30 18:14 UTC, mattleff commented on src/components/templates/andPlaybackContext.tsx
> -			} else if (videojs) {
@narthur I can reproduce the bug in Safari: 

1. In a Safari incognito window (or anywhere with uncached JS) open the site.
2. Click play on one of the home page recording cards.

### Expected result

The recording plays. This is the current behavior on the public website.

### Actual result

The recording loads the miniplayer but doesn't start playing.

2022-06-02 14:58 UTC, mattleff approved these changes
Can't reproduce the error anymore... Let's ship it and see if we get complaints.

2022-06-02 15:20 UTC, merged