Json ld and next-pwa tuning.
avorg/audioverse-next pull request #286
Opened 2022-05-16 04:59 UTC by bsalb

### Description
  - Here i have exclude the languages folder present inside public directory from being pre-cached. And added few more JSON-ld scripts for discover and similar pages with type Search box. I have also remove the aggregate rating from home page and localize the Audio verse slogan.

# To do:

- [ ] Exclude the languages from being pre-cached.
- [ ] Added localization in Home Page OG tags.
- [ ] Added more JSON-ld scripts
- [ ] Slightly improved initial bandwidth usage.

2022-05-16 13:37 UTC, narthur commented
@bsalb Apply the `ready-for-internal` label and then re-request reviews from Matthew and me when this is ready for review.

2022-05-17 13:38 UTC, narthur requested changes
Great work! Looks like you also need to fix the test suite.

2022-05-17 13:38 UTC, narthur commented on src/components/organisms/recording.tsx
> +			<CourseJsonLd
Not sure what the best place is to find info on JsonLd, but from this link I think course may be the wrong choice here:

https://jsonld.com/json-ld-course/

2022-05-17 13:38 UTC, narthur commented on src/containers/home.tsx
> +				// }}
I think we can delete `aggregateRating` entirely rather than commenting it out.

2022-05-17 13:38 UTC, narthur commented on src/containers/bible/versions.tsx
> +			<SiteLinksSearchBoxJsonLd
Still new to json ld, but should there just be one of these in home.tsx or something with all the actions in one place? Or is there an advantage to specifying the actions in different files?

2022-05-17 13:38 UTC, narthur commented on src/containers/bible/versions.tsx
> +			<SiteLinksSearchBoxJsonLd
Also, why are we defining the actions as searches, rather than directly linking to the page?

2022-05-18 09:30 UTC, bsalb commented on src/containers/home.tsx
> +				// }}
yes we can do that

2022-05-18 09:45 UTC, bsalb commented on src/containers/bible/versions.tsx
> +			<SiteLinksSearchBoxJsonLd
we have some unique json-ld type on each of pages. So, i provide these search types on them. Regarding the actions, i found search box common. so i provide query_input as per page. For example: in bible page search box searches for bibles.

2022-07-11 18:32 UTC, closed without merging