Helpscout
avorg/audioverse-next pull request #294
Opened 2022-06-02 15:29 UTC by narthur

2022-06-03 14:30 UTC, narthur commented
@mattleff I think the idea behind not having a backdrop is to allow the user to use the site while referring to a help article.

2022-06-03 14:45 UTC, narthur commented on .eslintrc.js
> +	ignorePatterns: ['**/*.js', 'src/lib/generated/**/*'],
I was trying to speed up the eslint run. Do you think we need to run eslint on graphql.ts?

2022-06-07 17:10 UTC, mattleff requested changes
LGTM! The lockfile is in version 1, once that's fixed let's ship it. 👍🏻

2022-06-07 17:10 UTC, mattleff commented on src/lib/useNavigationItems.tsx
> +// TODO: Find a way to reduce boilerplate without increasing bundle size
Do we need this comment?

2022-06-07 17:10 UTC, mattleff commented on src/styles/mixins.scss
> +$prefix: '-moz-', '-webkit-', '-o-', '-ms-', '';
I don't think we need these prefixes since Next uses autoprefixer automatically: https://nextjs.org/docs/advanced-features/customizing-postcss-config#default-behavior

2022-06-07 19:52 UTC, mattleff approved these changes
👍🏻 :shipit:

2022-06-07 20:15 UTC, merged