Add address to Contact page
avorg/audioverse-next pull request #338
Opened 2022-12-21 04:09 UTC by jlaverde77

Per Allister, adding address to Contact page and changing the blurb to mention address.

2022-12-21 21:35 UTC, narthur approved these changes

2022-12-28 14:11 UTC, narthur requested changes
Can you run `npm run extract` and `npm run compile` on this?

Otherwise looks great!

2022-12-28 15:18 UTC, jlaverde77 reviewed
Ran `npm run extract` and `npm run compile`. Then commited the changes to the files generated.

2022-12-28 16:49 UTC, narthur approved these changes
Great work!

2022-12-28 16:49 UTC, merged